language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN
script:
  - mvn -Dsonar.project.Key=edoreld-test_Dauphine-Open-Data -Dsonar.organization=edoreld-test-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2"

