language: java
jdk: oraclejdk8
notifications:
  slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC
addons:
  sonarcloud:
    organization: "edoreld-github"
    token:
      secure: "$SONAR_TOKEN"
script:
- mvn -Dsonar.login=$SONAR_TOKEN clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"

