language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "edoreld-test-github"
    secure:
      token: $SONAR_TOKEN
script:
  - mvn -Dsonar.login=$SONAR_TOKEN -Dsonar.password= clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"

