language: java
jdk: oraclejdk8
notifications:
  slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC
addons:
  sonarcloud:
    organization: "edoreld-github"
    token:
      secure: "$SONAR_TOKEN"
script:
- mvn -Dsonar.login=$SONAR_TOKEN -Dsonar.password= clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
cache:
  directories:
  - "$HOME/.m2"

