language: java
jdk: oraclejdk8
notifications:
    slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC
addons:
  sonarcloud:
    organization: "arnclaudel-github"
    secure:
      token: $SONAR_TOKEN
script:
  - mvn -Dsonar.login=$SONAR_TOKEN -Dsonar.password= -Dsonar.branch.name=dev clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
