language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "edoreld-test-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn -Dsonar.login=$SONAR_TOKEN clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2"

