env:
  global:
    secure: YCJxDlCue3Jy5Q2OfEyeabdTXfpJxJF79maMQYCt+JpFJFakv5OPlXMSfvUYbDzkd1Vg4uTXDkqDY018CTuIJHGmbX996vY0wbxUcnjPvCb+y1WOdMnpQhuEoH+7KvD1pxePRFgVQbJk5TZtO1D3oOhD/IKX10q6XqUofnWlTci7b9bWTp14MOIPoDhjvMStGaE5T012aq3OdSxLoxpl4JJFsv9g1L1fPOtX7nJZXQ6r5yQ+9dbbNNcM57DpEmW6T9HWJoKxPM3CmzDbEmP4ar4QG3xnrR1NFf6uyulnHQB2BNMB0WNiY+AsQwyjrNXg76DPClc9bYD+zGZcF78ZOB45jk+nxU92fWNAVNmcwTA1mD5hCNJNZUcxny0PYiL3IuaRX6uDXN3VkaFzF0GocEItJraIz85In8aAhnNz+aHoCD3ROEY6aMI/jAQde43kP2TpLyyEjwp9pDU6XSpnK3YBFBY8mSc90V89+6P2j9H4MCySP73BzrO4oX7Z4WbgRDU22UP89ynRMhjxFtFIBbEudECRl02B2/4li8ld+iw46cIdo332E7/L6qLZDh6AVfgZKJXo800bALRykinQFtI+VR18KefRArV56CMTQo7fBhJkBMSbf4BzmpfEPJzB1ShinD6Kzb+b4M0NJ8l2fB4QNdxiWgwaJXyOe2Vrr2o=
language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: edoreld-test-github
    token: "$SONAR_TOKEN"
script:
- mvn -Dsonar.projectKey=edoreld-test_Dauphine-Open-Data -Dsonar.organization=edoreld-test-github -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=$SONAR_TOKEN clean org.jacoco:jacoco-maven-plugin:prepare-agent
  install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
