language: java
jdk: oraclejdk8
notifications:
    slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC
addons:
  sonarcloud:
    organization: "edoreld-github"
    secure:
      token: $SONAR_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
